import { useState, useEffect } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { 
  FileCheck2, 
  RefreshCw, 
  Send, 
  ClipboardList, 
  FileText, 
  Presentation,
  Code2,
  Loader2,
  Download,
  FileJson,
  FileSpreadsheet,
  Mail,
  RotateCcw,
  Eye,
  Edit2,
  Paperclip
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { useToast } from "@/hooks/use-toast";
import type { Project, Scenario } from "@shared/schema";

interface ActionButtonsProps {
  project: Project | null | undefined;
  currentStage: number;
  isLoading?: boolean;
  onResetProject?: () => void;
}

export function ActionButtons({ project, currentStage, isLoading, onResetProject }: ActionButtonsProps) {
  const { toast } = useToast();
  const [emailDialogOpen, setEmailDialogOpen] = useState(false);
  const [emailPreviewOpen, setEmailPreviewOpen] = useState(false);
  const [clientEmail, setClientEmail] = useState(project?.clientEmail || "");
  const [emailSubject, setEmailSubject] = useState(`Project Proposal: ${project?.title || ""}`);
  const [emailBody, setEmailBody] = useState("");
  const [resetDialogOpen, setResetDialogOpen] = useState(false);

  // Generate default email preview content
  const generateDefaultEmailContent = () => {
    const scenario = project?.selectedScenario === "A" 
      ? project?.scenarioA as Scenario
      : project?.scenarioB as Scenario;
    
    return `Dear ${project?.clientName || "Team"},

Thank you for the opportunity to discuss your project. I'm excited to share our proposal for ${project?.title || "your project"}.

After careful analysis, we recommend the ${scenario?.name || "selected approach"}, which offers:
${(scenario?.pros || []).slice(0, 3).map(p => `- ${p}`).join("\n") || "- Tailored solution for your needs"}

Investment: ${scenario?.totalCost ? `$${scenario.totalCost.toLocaleString()}` : "To be discussed"}
Timeline: ${scenario?.timeline || "To be determined"}

The attached proposal contains detailed information about features, timeline, and our recommended approach.

I'd love to schedule a call to walk you through the proposal and answer any questions.

Best regards,
ISI Agent

---
This proposal was generated by ISI, your autonomous Business Development Agent.`;
  };

  // Initialize email body when opening preview
  useEffect(() => {
    if (emailPreviewOpen && !emailBody) {
      setEmailBody(generateDefaultEmailContent());
    }
  }, [emailPreviewOpen]);

  const updateClientEmail = useMutation({
    mutationFn: async (email: string) => {
      await apiRequest("POST", `/api/projects/${project?.id}/update-client-email`, { email });
      return email;
    },
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      toast({
        title: "Email Updated",
        description: "Client email saved.",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to update client email",
        variant: "destructive",
      });
    },
  });

  const approveEstimate = useMutation({
    mutationFn: async () => {
      const response = await fetch(`/api/projects/${project?.id}/approve-estimate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
      });
      if (!response.ok) {
        throw new Error("Failed to approve estimate");
      }
      return response.json() as Promise<{ proposalPdfUrl?: string }>;
    },
    onSuccess: async (data: { proposalPdfUrl?: string }) => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      queryClient.invalidateQueries({ queryKey: ["/api/projects/recent"] });
      
      // Trigger PDF download if URL is available
      if (data?.proposalPdfUrl) {
        try {
          const response = await fetch(data.proposalPdfUrl);
          const blob = await response.blob();
          const url = window.URL.createObjectURL(blob);
          const link = document.createElement("a");
          link.href = url;
          link.download = `${project?.title || "proposal"}_proposal.pdf`;
          document.body.appendChild(link);
          link.click();
          document.body.removeChild(link);
          window.URL.revokeObjectURL(url);
          
          toast({
            title: "PDF Generated & Downloaded",
            description: "Your proposal PDF has been saved to your downloads folder.",
          });
        } catch {
          toast({
            title: "Estimate Approved",
            description: "PDF generated. You can download it from the Export menu.",
          });
        }
      } else {
        toast({
          title: "Estimate Approved",
          description: "Moving to production assets generation...",
        });
      }
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to approve estimate",
        variant: "destructive",
      });
    },
  });
  
  const resetProject = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", `/api/projects/${project?.id}/reset`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id, "messages"] });
      queryClient.invalidateQueries({ queryKey: ["/api/projects/recent"] });
      setResetDialogOpen(false);
      toast({
        title: "Project Reset",
        description: "Starting fresh from the beginning.",
      });
      onResetProject?.();
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to reset project",
        variant: "destructive",
      });
    },
  });

  const regenerateEstimate = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", `/api/projects/${project?.id}/regenerate-estimate`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      toast({
        title: "Regenerating",
        description: "Creating a new estimate...",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to regenerate estimate",
        variant: "destructive",
      });
    },
  });

  const generateAssets = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", `/api/projects/${project?.id}/generate-assets`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      toast({
        title: "Assets Generated",
        description: "PDFs and presentation are ready!",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate assets",
        variant: "destructive",
      });
    },
  });

  const sendEmailWithRecipient = useMutation({
    mutationFn: async ({ recipientEmail, subject, body }: { recipientEmail: string; subject: string; body: string }) => {
      return await apiRequest("POST", `/api/projects/${project?.id}/send-email`, { 
        recipientEmail, 
        emailSubject: subject,
        emailBody: body 
      });
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      setEmailPreviewOpen(false);
      toast({
        title: "Email Sent",
        description: "Proposal sent to client successfully!",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to send email",
        variant: "destructive",
      });
    },
  });

  const handleOpenEmailPreview = () => {
    setClientEmail(project?.clientEmail || "");
    setEmailSubject(`Project Proposal: ${project?.title || ""}`);
    setEmailBody(generateDefaultEmailContent());
    
    if (!project?.clientEmail) {
      setEmailDialogOpen(true);
    } else {
      setEmailPreviewOpen(true);
    }
  };

  const handleSendFromPreview = () => {
    if (!clientEmail || !clientEmail.includes("@")) {
      toast({
        title: "Invalid Email",
        description: "Please provide a valid email address.",
        variant: "destructive",
      });
      return;
    }
    sendEmailWithRecipient.mutate({ 
      recipientEmail: clientEmail, 
      subject: emailSubject, 
      body: emailBody 
    });
  };

  const generateVibeGuide = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", `/api/projects/${project?.id}/generate-vibe-guide`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      toast({
        title: "Guide Generated",
        description: "Vibecoding execution guide is ready!",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate guide",
        variant: "destructive",
      });
    },
  });

  const generatePMBreakdown = useMutation({
    mutationFn: async () => {
      return await apiRequest("POST", `/api/projects/${project?.id}/generate-pm-breakdown`);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/projects", project?.id] });
      toast({
        title: "PM Breakdown Generated",
        description: "Project management plan is ready!",
      });
    },
    onError: (error) => {
      toast({
        title: "Error",
        description: error.message || "Failed to generate PM breakdown",
        variant: "destructive",
      });
    },
  });

  if (!project || isLoading) {
    return null;
  }

  const isPending = 
    approveEstimate.isPending || 
    regenerateEstimate.isPending || 
    generateAssets.isPending || 
    sendEmailWithRecipient.isPending ||
    updateClientEmail.isPending ||
    generateVibeGuide.isPending || 
    generatePMBreakdown.isPending ||
    resetProject.isPending;

  return (
    <div className="flex items-center gap-3 flex-wrap justify-end" data-testid="action-buttons">
      {currentStage === 1 && project.estimateMarkdown && (
        <>
          <Button
            variant="outline"
            onClick={() => setResetDialogOpen(true)}
            disabled={isPending}
            data-testid="button-start-from-zero"
          >
            {resetProject.isPending ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <RotateCcw className="h-4 w-4 mr-2" />
            )}
            Start from 0
          </Button>
          <Button
            variant="glass"
            onClick={() => regenerateEstimate.mutate()}
            disabled={isPending}
            data-testid="button-regenerate"
          >
            {regenerateEstimate.isPending ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <RefreshCw className="h-4 w-4 mr-2" />
            )}
            Regenerate
          </Button>
          <Button
            variant="glass-primary"
            onClick={() => approveEstimate.mutate()}
            disabled={isPending}
            data-testid="button-approve"
          >
            {approveEstimate.isPending ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <FileCheck2 className="h-4 w-4 mr-2" />
            )}
            Approve & Generate PDF
          </Button>
        </>
      )}

      {currentStage === 2 && (
        <>
          {project.proposalPdfUrl && (
            <Button variant="glass" asChild data-testid="button-download-proposal">
              <a href={project.proposalPdfUrl} target="_blank" rel="noopener noreferrer">
                <Download className="h-4 w-4 mr-2" />
                Download Proposal
              </a>
            </Button>
          )}
          {project.presentationUrl && (
            <Button variant="glass" asChild data-testid="button-view-presentation">
              <a href={project.presentationUrl} target="_blank" rel="noopener noreferrer">
                <Presentation className="h-4 w-4 mr-2" />
                View Presentation
              </a>
            </Button>
          )}
          <Button
            variant="glass-primary"
            onClick={handleOpenEmailPreview}
            disabled={isPending}
            data-testid="button-send-email"
          >
            {sendEmailWithRecipient.isPending ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <Eye className="h-4 w-4 mr-2" />
            )}
            Preview & Send Email
          </Button>
        </>
      )}

      {currentStage === 3 && (
        <Button
          variant="glass-primary"
          onClick={() => generateVibeGuide.mutate()}
          disabled={isPending}
          data-testid="button-generate-vibe-guide"
        >
          {generateVibeGuide.isPending ? (
            <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          ) : (
            <Code2 className="h-4 w-4 mr-2" />
          )}
          Generate Execution Guide
        </Button>
      )}

      {currentStage === 4 && (
        <>
          {project.vibecodeGuideA && (
            <Button variant="glass" data-testid="button-view-guide-a">
              <FileText className="h-4 w-4 mr-2" />
              Manual A (High-Code)
            </Button>
          )}
          {project.vibecodeGuideB && (
            <Button variant="glass" data-testid="button-view-guide-b">
              <FileText className="h-4 w-4 mr-2" />
              Manual B (No-Code)
            </Button>
          )}
          <Button
            variant="glass-primary"
            onClick={() => generatePMBreakdown.mutate()}
            disabled={isPending}
            data-testid="button-generate-pm"
          >
            {generatePMBreakdown.isPending ? (
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
            ) : (
              <ClipboardList className="h-4 w-4 mr-2" />
            )}
            Generate PM Tracks
          </Button>
        </>
      )}

      {currentStage === 5 && (
        <>
          {!project.pmBreakdown ? (
            <Button
              variant="glass-primary"
              onClick={() => generatePMBreakdown.mutate()}
              disabled={isPending}
              data-testid="button-generate-pm-final"
            >
              {generatePMBreakdown.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <ClipboardList className="h-4 w-4 mr-2" />
              )}
              Generate PM Breakdown
            </Button>
          ) : (
            <Button variant="glass" disabled className="bg-green-500/20 border-green-500/50 text-green-600" data-testid="button-pm-completed">
              <FileCheck2 className="h-4 w-4 mr-2" />
              PM Breakdown Complete
            </Button>
          )}
        </>
      )}

      {project && (
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" data-testid="button-export">
              <Download className="h-4 w-4 mr-2" />
              Export
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem asChild>
              <a 
                href={`/api/projects/${project.id}/export/json`} 
                download
                className="flex items-center gap-2"
                data-testid="button-export-json"
              >
                <FileJson className="h-4 w-4" />
                Export as JSON
              </a>
            </DropdownMenuItem>
            <DropdownMenuItem asChild>
              <a 
                href={`/api/projects/${project.id}/export/csv`}
                download
                className="flex items-center gap-2"
                data-testid="button-export-csv"
              >
                <FileSpreadsheet className="h-4 w-4" />
                Export Estimates (CSV)
              </a>
            </DropdownMenuItem>
            {project.proposalPdfUrl && (
              <DropdownMenuItem asChild>
                <a 
                  href={project.proposalPdfUrl}
                  download
                  className="flex items-center gap-2"
                  data-testid="button-export-proposal-pdf"
                >
                  <FileText className="h-4 w-4" />
                  Download Proposal PDF
                </a>
              </DropdownMenuItem>
            )}
            {project.internalReportPdfUrl && (
              <DropdownMenuItem asChild>
                <a 
                  href={project.internalReportPdfUrl}
                  download
                  className="flex items-center gap-2"
                  data-testid="button-export-report-pdf"
                >
                  <FileText className="h-4 w-4" />
                  Download Internal Report
                </a>
              </DropdownMenuItem>
            )}
          </DropdownMenuContent>
        </DropdownMenu>
      )}

      <Dialog open={emailDialogOpen} onOpenChange={setEmailDialogOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Client Email Required
            </DialogTitle>
            <DialogDescription>
              Please provide the client's email address to send the proposal.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="client-email">Email Address</Label>
              <Input
                id="client-email"
                type="email"
                placeholder="client@example.com"
                value={clientEmail}
                onChange={(e) => setClientEmail(e.target.value)}
                data-testid="input-client-email"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setEmailDialogOpen(false)} data-testid="button-cancel-email">
              Cancel
            </Button>
            <Button 
              onClick={() => {
                if (clientEmail && clientEmail.includes("@")) {
                  updateClientEmail.mutate(clientEmail);
                  setEmailDialogOpen(false);
                  setEmailSubject(`Project Proposal: ${project?.title || ""}`);
                  setEmailBody(generateDefaultEmailContent());
                  setEmailPreviewOpen(true);
                }
              }}
              disabled={!clientEmail || !clientEmail.includes('@') || updateClientEmail.isPending}
              data-testid="button-save-email"
            >
              {updateClientEmail.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : null}
              Continue to Preview
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={emailPreviewOpen} onOpenChange={setEmailPreviewOpen}>
        <DialogContent className="sm:max-w-[700px] max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Email Preview
            </DialogTitle>
            <DialogDescription>
              Review and edit the email before sending. The proposal PDF will be attached.
            </DialogDescription>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="recipient-email">To</Label>
              <Input
                id="recipient-email"
                type="email"
                placeholder="client@example.com"
                value={clientEmail}
                onChange={(e) => setClientEmail(e.target.value)}
                data-testid="input-recipient-email"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email-subject">Subject</Label>
              <Input
                id="email-subject"
                type="text"
                value={emailSubject}
                onChange={(e) => setEmailSubject(e.target.value)}
                data-testid="input-email-subject"
              />
            </div>
            <div className="grid gap-2">
              <Label htmlFor="email-body">Message</Label>
              <Textarea
                id="email-body"
                value={emailBody}
                onChange={(e) => setEmailBody(e.target.value)}
                className="min-h-[250px] font-mono text-sm"
                data-testid="input-email-body"
              />
            </div>
            <div className="flex items-center gap-2 p-3 rounded-md bg-muted text-sm">
              <Paperclip className="h-4 w-4 text-muted-foreground" />
              <span className="text-muted-foreground">Attachment:</span>
              <span className="font-medium">{project?.title?.replace(/[^a-zA-Z0-9]/g, "_")}_proposal.pdf</span>
            </div>
          </div>
          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setEmailPreviewOpen(false)} data-testid="button-cancel-preview">
              Cancel
            </Button>
            <Button 
              onClick={handleSendFromPreview}
              disabled={!clientEmail || !clientEmail.includes('@') || sendEmailWithRecipient.isPending}
              data-testid="button-send-email-final"
            >
              {sendEmailWithRecipient.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Send className="h-4 w-4 mr-2" />
              )}
              Send Email
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={resetDialogOpen} onOpenChange={setResetDialogOpen}>
        <DialogContent className="sm:max-w-[425px]">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <RotateCcw className="h-5 w-5" />
              Start from 0?
            </DialogTitle>
            <DialogDescription>
              This will clear all generated content for this project and start fresh from the beginning. Your chat history will be preserved.
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setResetDialogOpen(false)} data-testid="button-cancel-reset">
              Cancel
            </Button>
            <Button 
              variant="destructive"
              onClick={() => resetProject.mutate()}
              disabled={resetProject.isPending}
              data-testid="button-confirm-reset"
            >
              {resetProject.isPending ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <RotateCcw className="h-4 w-4 mr-2" />
              )}
              Reset Project
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
